### ISSUE TITLE
1.1.1 Override NodeController with routing configuration won't work

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1712]
When I want to override NodeController but overriding the route did not work:

```
open_orchestra_front_node:
    path: /node/{nodeId}
    defaults: { _controller: MyFrontBundle:Node:show }
    methods: [GET]
```
I have to override open_orchestra_front.router.document_to_value_object.class to do the job.
